"""remove register_date from User model.

Revision ID: f2b763dec185
Revises: 8a568ca70e8c
Create Date: 2017-09-18 18:12:07.480886

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2b763dec185'
down_revision = '8a568ca70e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'register_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('register_date', sa.DATETIME(), nullable=True))
    # ### end Alembic commands ###
